### ISSUE TITLE
Remove usage of nii_tools

### ISSUE THREAD

**Issue by lawlessrd** [ALXXLARG/FCT#1]
The niitools package used in this pipeline are outdated and often result in errors and incorrect data. Please remove all uses of niitools functions (load_nii, load_untoch_nii, save_untoch_nii), and replace them with either the built in matlab functions (niftiread, niftiwrite) or the appropriate spm functions (spm_vol, spm_reslice).  If you need a reference for how some of these functions are used, please see the finalized SCZ_WM main function here: https://github.com/lawlessrd/SCZ-WM-pipeline/blob/main/matlab/src/scz_main.m. Additionally, here is a link to a repo of the SPM functions which may be of use to you (though you won't have to add these to the repo, they should already be in the SPM12 package, this is just a helpful reference/example).

Let me know if you have any questions.

**Comment by lawlessrd** [comment]
Forgot to include the SPM link: https://github.com/VUIIS/spm_readwrite_nii

**Comment by ALXXLARG** [comment]
OK. I will do that. Thanks!

**Comment by lawlessrd** [comment]
No problem. If you need any help with removing these functions or github in general feel free to reach out.

**Comment by ALXXLARG** [comment]
OK!

**Comment by ALXXLARG** [comment]
Hello,

I think I have removed all uses of niitool functions. I am wondering if you could have a look. Please let me know if there are any more issues.

Thank you very much for your help!
